name: Build and Push Docker Images
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
   types: [labeled]
   
jobs:
  build-and-push:
   runs-on: ubuntu-latest
   strategy:
    matrix:
     include:
      - image_name: db
        dockerfile: db/Dockerfile
      - image_name: web
        dockerfile: web/Dockerfile
      - image_name: words
        dockerfile: words/Dockerfile
   steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./${{ matrix.dockerfile }}
        push: true
        tags: ibrahimkr/${{ matrix.image_name }}:db, ibrahimkr/${{ matrix.image_name }}:web, ibrahimkr/${{ matrix.image_name }}:words

 